namespace YALCINDORSE.Services
{
    /// <summary>OM (teklif formu) tablosundaki bir satir — section header veya urun item.</summary>
    public class OmRow
    {
        public string   Tip        { get; set; } = "ITEM";   // "SECTION" or "ITEM"
        public string   Kod        { get; set; } = "";       // LB2, A001 vb. (SECTION'da bos)
        public string   Aciklama   { get; set; } = "";       // ana metin
        public string   Detay      { get; set; } = "";       // ikincil aciklama (col 3)
        public decimal? BirimFiyat { get; set; }             // SECTION'da null
    }

    /// <summary>
    /// barandrive/OM_TR.xlsx ve OM_EN.xlsx kaynakli teklif formu/fiyat listesi verisi.
    /// PDF teklif sonuna eklenir (Dil = TR/EN). DE/FR/RU icin TR dusulur (fallback).
    /// </summary>
    public static class OmFormVerileri
    {
        public static readonly List<OmRow> TR = new()
        {
            new() { Tip="SECTION", Kod="", Aciklama="FİYAT LİSTESİ BPW VEYA SAF AKSLARLA", Detay="", BirimFiyat=null },
            new() { Tip="ITEM", Kod="LB2", Aciklama="2 Aks Lowbed Yarı Römork", Detay="1 Sabit - 1 Kendinden Döner Aks BPW veya SAF", BirimFiyat=50000.0m },
            new() { Tip="ITEM", Kod="LB3", Aciklama="3 Aks Lowbed Yarı Römork", Detay="2 Sabit - 1 Kendinden Döner Aks BPW veya SAF", BirimFiyat=53700.0m },
            new() { Tip="ITEM", Kod="LB4", Aciklama="4 Aks Lowbed Yarı Römork", Detay="2 Sabit - 2 Kendinden Döner Aks BPW veya SAF", BirimFiyat=60900.0m },
            new() { Tip="ITEM", Kod="LB5", Aciklama="5 Aks Lowbed Yarı Römork", Detay="3 Sabit - 2 Kendinden Döner Aks BPW veya SAF", BirimFiyat=67700.0m },
            new() { Tip="ITEM", Kod="LB5", Aciklama="5 Aks Lowbed Yarı Römork", Detay="2 Sabit - 3 Kendinden Döner Aks BPW veya SAF", BirimFiyat=71500.0m },
            new() { Tip="ITEM", Kod="LB6", Aciklama="6 Aks Lowbed Yarı Römork", Detay="3 Sabit - 3 Kendinden Döner Aks BPW veya SAF", BirimFiyat=79000.0m },
            new() { Tip="ITEM", Kod="LB6", Aciklama="6 Aks Lowbed Yarı Römork", Detay="2 Sabit - 4 Kendinden Döner Aks BPW veya SAF", BirimFiyat=82800.0m },
            new() { Tip="ITEM", Kod="LL2", Aciklama="2 Aks Low Loader Yarı Römork", Detay="2 Hidrolik Dümenlenir Aks BPW veya SAF", BirimFiyat=106000.0m },
            new() { Tip="ITEM", Kod="LL3", Aciklama="3 Aks Low Loader Yarı Römork", Detay="3 Hidrolik Dümenlenir Aks BPW veya SAF", BirimFiyat=130000.0m },
            new() { Tip="ITEM", Kod="LL4", Aciklama="4 Aks Low Loader Yarı Römork", Detay="4 Hidrolik Dümenlenir Aks BPW veya SAF", BirimFiyat=154000.0m },
            new() { Tip="ITEM", Kod="LL4", Aciklama="4 Aks Low Loader Yarı Römork", Detay="4 Hidrolik Dümenlenir Aks (Ağır Görev Tipi) BPW veya SAF", BirimFiyat=169000.0m },
            new() { Tip="SECTION", Kod="", Aciklama="FİYAT LİSTESİ TÜRK MALI AKSLAR İLE", Detay="", BirimFiyat=null },
            new() { Tip="ITEM", Kod="TR2", Aciklama="2 Aks Lowbed Yarı Römork", Detay="1 Sabit - 1 Kendinden Döner Aks TÜRK MALI AKSLAR", BirimFiyat=46500.0m },
            new() { Tip="ITEM", Kod="TR3", Aciklama="3 Aks Lowbed Yarı Römork", Detay="2 Sabit - 1 Kendinden Döner Aks TÜRK MALI AKSLAR", BirimFiyat=49200.0m },
            new() { Tip="ITEM", Kod="TR4", Aciklama="4 Aks Lowbed Yarı Römork", Detay="2 Sabit - 2 Kendinden Döner Aks TÜRK MALI AKSLAR", BirimFiyat=53900.0m },
            new() { Tip="ITEM", Kod="TR5", Aciklama="5 Aks Lowbed Yarı Römork", Detay="3 Sabit - 2 Kendinden Döner Aks TÜRK MALI AKSLAR", BirimFiyat=59700.0m },
            new() { Tip="ITEM", Kod="TR5", Aciklama="5 Aks Lowbed Yarı Römork", Detay="2 Sabit - 3 Kendinden Döner Aks TÜRK MALI AKSLAR", BirimFiyat=62000.0m },
            new() { Tip="ITEM", Kod="TR6", Aciklama="6 Aks Lowbed Yarı Römork", Detay="3 Sabit - 3 Kendinden Döner Aks TÜRK MALI AKSLAR", BirimFiyat=68500.0m },
            new() { Tip="SECTION", Kod="", Aciklama="OPSİYONEL ÖZELLİKLER", Detay="", BirimFiyat=null },
            new() { Tip="ITEM", Kod="A001", Aciklama="Tek uzar yükleme platformu", Detay="", BirimFiyat=7200.0m },
            new() { Tip="ITEM", Kod="A002", Aciklama="Çift uzar yükleme platformu", Detay="", BirimFiyat=25000.0m },
            new() { Tip="ITEM", Kod="A003", Aciklama="Hidrolik, ağır görev tipi, tek parça yükleme rampaları", Detay="", BirimFiyat=5100.0m },
            new() { Tip="ITEM", Kod="A004", Aciklama="Hidrolik, ağır görev tipi, çift parça yükleme rampaları", Detay="", BirimFiyat=7100.0m },
            new() { Tip="ITEM", Kod="A005", Aciklama="Hidrolik, hafif görev tipi, çift parça yükleme rampaları", Detay="", BirimFiyat=6350.0m },
            new() { Tip="ITEM", Kod="A006", Aciklama="Hidrolik olarak içe ve dışa kayar yükleme rampaları", Detay="", BirimFiyat=1650.0m },
            new() { Tip="ITEM", Kod="A007", Aciklama="Sökülebilir yükleme rampaları (5 dk içinde hızlı sökme ve takma)", Detay="", BirimFiyat=4650.0m },
            new() { Tip="ITEM", Kod="A008", Aciklama="Çifti 20 ton kapasiteli alüminyum yükleme rampaları", Detay="", BirimFiyat=2000.0m },
            new() { Tip="ITEM", Kod="A009", Aciklama="Çifti 30 ton kapasiteli alüminyum yükleme rampaları", Detay="", BirimFiyat=2500.0m },
            new() { Tip="ITEM", Kod="A010", Aciklama="Yükleme rampaları için sıcak daldırma galvaniz kaplama", Detay="", BirimFiyat=1150.0m },
            new() { Tip="ITEM", Kod="A011", Aciklama="Boyalı, kısa, çelik ön duvar", Detay="", BirimFiyat=650.0m },
            new() { Tip="ITEM", Kod="A012", Aciklama="Galvaniz kaplı, kısa, çelik ön duvar", Detay="", BirimFiyat=750.0m },
            new() { Tip="ITEM", Kod="A013", Aciklama="Galvaniz kaplı, uzun, çelik ön duvar", Detay="", BirimFiyat=900.0m },
            new() { Tip="ITEM", Kod="A014", Aciklama="Takım dolabı formunda çelik ön duvar", Detay="", BirimFiyat=1350.0m },
            new() { Tip="ITEM", Kod="A015", Aciklama="Geçme tip, alüminyum yan kapaklar", Detay="", BirimFiyat=500.0m },
            new() { Tip="ITEM", Kod="A016", Aciklama="Aşağı açılır tip, alüminyum yan kapaklar", Detay="", BirimFiyat=600.0m },
            new() { Tip="ITEM", Kod="A017", Aciklama="Aşağı açılır tip, alüminyum yan kapaklar KINNEGRIP babalı", Detay="", BirimFiyat=1300.0m },
            new() { Tip="ITEM", Kod="A018", Aciklama="Geçme tip, alüminyum arka kapak", Detay="", BirimFiyat=250.0m },
            new() { Tip="ITEM", Kod="A019", Aciklama="Alüminyum, deveboynu tırmanma rampası", Detay="", BirimFiyat=1050.0m },
            new() { Tip="ITEM", Kod="A020", Aciklama="Çelik, deveboynu tırmanma rampası", Detay="", BirimFiyat=400.0m },
            new() { Tip="ITEM", Kod="A021", Aciklama="Hidrolik olarak kaldırılabilir deveboynu tırmanma platformu", Detay="", BirimFiyat=6500.0m },
            new() { Tip="ITEM", Kod="A022", Aciklama="1 çift 18 ton kapasiteli alüminyum köprü U: 1.000 mm", Detay="", BirimFiyat=2100.0m },
            new() { Tip="ITEM", Kod="A023", Aciklama="1 çift teker havuzu ve galvaniz kaplı çelik çerçeveli ahşap kapaklar", Detay="", BirimFiyat=3100.0m },
            new() { Tip="ITEM", Kod="A024", Aciklama="Ekskavatör bom havuzu", Detay="", BirimFiyat=2250.0m },
            new() { Tip="ITEM", Kod="A025", Aciklama="Galvaniz kaplı çelik çerçeveli yana genişleme ahşapları", Detay="", BirimFiyat=1550.0m },
            new() { Tip="ITEM", Kod="A026", Aciklama="Çerçevesiz yana genişleme ahşapları", Detay="", BirimFiyat=1100.0m },
            new() { Tip="ITEM", Kod="A027", Aciklama="Döner tip konteyner kilidi", Detay="", BirimFiyat=280.0m },
            new() { Tip="ITEM", Kod="A028", Aciklama="İskandinav tip konteyner kilidi", Detay="", BirimFiyat=280.0m },
            new() { Tip="ITEM", Kod="A029", Aciklama="Marina tipi konteyner kilidi", Detay="", BirimFiyat=140.0m },
            new() { Tip="ITEM", Kod="A030", Aciklama="Marina tipi konteyner kilidi için slot", Detay="", BirimFiyat=140.0m },
            new() { Tip="ITEM", Kod="A031", Aciklama="Deveboynu ve yükleme platformunu hizalamak için sehpa (kilitler ile uyumlu)", Detay="", BirimFiyat=1750.0m },
            new() { Tip="ITEM", Kod="A032", Aciklama="Deveboynu ve yükleme plaftormu yanlarında baba yuvaları", Detay="", BirimFiyat=650.0m },
            new() { Tip="ITEM", Kod="A033", Aciklama="Yükleme platformu üzerinde baba yuvası grupları", Detay="", BirimFiyat=750.0m },
            new() { Tip="ITEM", Kod="A034", Aciklama="Sıcak daldırma galvaniz kaplı baba seti ve tutucuları", Detay="", BirimFiyat=1250.0m },
            new() { Tip="ITEM", Kod="A035", Aciklama="1 adet siyah boyalı çelik takım dolabı", Detay="", BirimFiyat=350.0m },
            new() { Tip="ITEM", Kod="A036", Aciklama="1 adet paslanmaz çelik (INOX) takım dolabı", Detay="", BirimFiyat=600.0m },
            new() { Tip="ITEM", Kod="A037", Aciklama="Sıcak daldırma galvaniz kaplı açık ekipman dolabı", Detay="", BirimFiyat=600.0m },
            new() { Tip="ITEM", Kod="A038", Aciklama="Sıcak daldırma galvaniz kaplı platform genişliğinde açık ekipman dolabı", Detay="", BirimFiyat=1250.0m },
            new() { Tip="ITEM", Kod="A039", Aciklama="1 adet paslanmaz çelik (INOX), deveboynu üstünde takım dolabı", Detay="", BirimFiyat=1200.0m },
            new() { Tip="ITEM", Kod="A040", Aciklama="15 ton kapasiteli, çift devirli hidrolik vinç ve uzaktan kumandası", Detay="", BirimFiyat=5500.0m },
            new() { Tip="ITEM", Kod="A041", Aciklama="13 ton kapasiteli elektrikli vinç ve uzaktan kumandası", Detay="", BirimFiyat=2150.0m },
            new() { Tip="ITEM", Kod="A042", Aciklama="10 ton kapasiteli elektrikli vinç ve uzaktan kumandası", Detay="", BirimFiyat=1400.0m },
            new() { Tip="ITEM", Kod="A043", Aciklama="8 ton kapasiteli elektrikli vinç ve uzaktan kumandası", Detay="", BirimFiyat=1200.0m },
            new() { Tip="ITEM", Kod="A044", Aciklama="1 adet kalkar aks", Detay="", BirimFiyat=800.0m },
            new() { Tip="ITEM", Kod="A045", Aciklama="1 adet stepne ve tutucusu", Detay="", BirimFiyat=450.0m },
            new() { Tip="ITEM", Kod="A046", Aciklama="Alüminyum jantlar ALCOA DURA BRIGHT", Detay="", BirimFiyat=550.0m },
            new() { Tip="ITEM", Kod="A047", Aciklama="Kilometre sayacı BPW, SAF veya JOST", Detay="", BirimFiyat=300.0m },
            new() { Tip="ITEM", Kod="A048", Aciklama="SAF akslar için lastik basıncı tamamlama sistemi 2 aks için", Detay="", BirimFiyat=2300.0m },
            new() { Tip="ITEM", Kod="A049", Aciklama="SAF akslar için lastik basıncı tamamlama sistemi 3 aks için", Detay="", BirimFiyat=2700.0m },
            new() { Tip="ITEM", Kod="A050", Aciklama="SAF akslar için lastik basıncı tamamlama sistemi 4 aks için", Detay="", BirimFiyat=3100.0m },
            new() { Tip="ITEM", Kod="A051", Aciklama="SAF akslar için lastik basıncı tamamlama sistemi 5 aks için", Detay="", BirimFiyat=3500.0m },
            new() { Tip="ITEM", Kod="A052", Aciklama="SAF akslar için lastik basıncı tamamlama sistemi 6 aks için", Detay="", BirimFiyat=4500.0m },
            new() { Tip="ITEM", Kod="A053", Aciklama="Hidrolik veya elektro-hidrolik dümenleme sistemi TRIDEC veya VSE 2 aks için", Detay="", BirimFiyat=33000.0m },
            new() { Tip="ITEM", Kod="A054", Aciklama="Hidrolik veya elektro-hidrolik dümenleme sistemi TRIDEC veya VSE 3 aks için", Detay="", BirimFiyat=43000.0m },
            new() { Tip="ITEM", Kod="A055", Aciklama="Hidrolik veya elektro-hidrolik dümenleme sistemi TRIDEC veya VSE 4 aks için", Detay="", BirimFiyat=51000.0m },
            new() { Tip="ITEM", Kod="A056", Aciklama="Hidrolik veya elektro-hidrolik dümenleme sistemi TRIDEC veya VSE 5 aks için", Detay="", BirimFiyat=61000.0m },
            new() { Tip="ITEM", Kod="A057", Aciklama="Hidrolik veya elektro-hidrolik dümenleme sistemi TRIDEC veya VSE 6 aks için", Detay="", BirimFiyat=71000.0m },
            new() { Tip="ITEM", Kod="A058", Aciklama="Hidrolik veya elektro-hidrolik dümenleme sistemi TRIDEC veya VSE 7 aks için", Detay="", BirimFiyat=81000.0m },
            new() { Tip="ITEM", Kod="A059", Aciklama="Hava yerine hidrolik süspansiyon sistemi", Detay="", BirimFiyat=5000.0m },
            new() { Tip="ITEM", Kod="A060", Aciklama="4 adet uzayabilir geniş yük uyarı levhası", Detay="", BirimFiyat=1050.0m },
            new() { Tip="ITEM", Kod="A061", Aciklama="\"CONVOI EXCEPTIONNEL\" yazılı reflektif lamba", Detay="", BirimFiyat=450.0m },
            new() { Tip="ITEM", Kod="A062", Aciklama="4 adet yerine 6 adet hamburger tipi stop lambası", Detay="", BirimFiyat=150.0m },
            new() { Tip="ITEM", Kod="A063", Aciklama="Tek pompalı otomatik yağlama sistemi GROENEVELD", Detay="", BirimFiyat=2800.0m },
            new() { Tip="ITEM", Kod="A064", Aciklama="Çift pompalı otomatik yağlama sistemi GROENEVELD", Detay="", BirimFiyat=3500.0m },
            new() { Tip="ITEM", Kod="A065", Aciklama="Smart Board WABCO", Detay="", BirimFiyat=400.0m },
            new() { Tip="ITEM", Kod="A066", Aciklama="Full şasi %85 çinko, %15 alüminyum karışımlı metalizasyon (15 yıl anti-pas garantili)", Detay="", BirimFiyat=3000.0m },
            new() { Tip="ITEM", Kod="A067", Aciklama="Kısmi %85 çinko, %15 alüminyum karışımlı metalizasyon (15 yıl anti-pas garantili)", Detay="", BirimFiyat=1000.0m },
            new() { Tip="ITEM", Kod="A068", Aciklama="Yükleme platformu kuyruğu altında hidrolik destek ayakları", Detay="", BirimFiyat=2250.0m },
            new() { Tip="ITEM", Kod="A069", Aciklama="Hidrolik deveboynu", Detay="", BirimFiyat=8900.0m },
        };

        public static readonly List<OmRow> EN = new()
        {
            new() { Tip="SECTION", Kod="", Aciklama="PRICE LIST WITH BPW OR SAF AXLES", Detay="", BirimFiyat=null },
            new() { Tip="ITEM", Kod="LB2", Aciklama="2 Axles Lowbed Semi Trailer", Detay="1 Fixed - 1 Self Steering Axle BPW or SAF", BirimFiyat=50000.0m },
            new() { Tip="ITEM", Kod="LB3", Aciklama="3 Axles Lowbed Semi Trailer", Detay="2 Fixed - 1 Self Steering Axle BPW or SAF", BirimFiyat=53700.0m },
            new() { Tip="ITEM", Kod="LB4", Aciklama="4 Axles Lowbed Semi Trailer", Detay="2 Fixed - 2 Self Steering Axle BPW or SAF", BirimFiyat=60900.0m },
            new() { Tip="ITEM", Kod="LB5", Aciklama="5 Axles Lowbed Semi Trailer", Detay="3 Fixed - 2 Self Steering Axle BPW or SAF", BirimFiyat=67700.0m },
            new() { Tip="ITEM", Kod="LB5", Aciklama="5 Axles Lowbed Semi Trailer", Detay="2 Fixed - 3 Self Steering Axle BPW or SAF", BirimFiyat=71500.0m },
            new() { Tip="ITEM", Kod="LB6", Aciklama="6 Axles Lowbed Semi Trailer", Detay="3 Fixed - 3 Self Steering Axle BPW or SAF", BirimFiyat=79000.0m },
            new() { Tip="ITEM", Kod="LB6", Aciklama="6 Axles Lowbed Semi Trailer", Detay="2 Fixed - 4 Self Steering Axle BPW or SAF", BirimFiyat=82800.0m },
            new() { Tip="ITEM", Kod="LL2", Aciklama="2 Axles Low Loader Semi Trailer", Detay="2 Hydraulic Steering Axles BPW or SAF", BirimFiyat=106000.0m },
            new() { Tip="ITEM", Kod="LL3", Aciklama="3 Axles Low Loader Semi Trailer", Detay="3 Hydraulic Steering Axles BPW or SAF", BirimFiyat=130000.0m },
            new() { Tip="ITEM", Kod="LL4", Aciklama="4 Axles Low Loader Semi Trailer", Detay="4 Hydraulic Steering Axles BPW or SAF", BirimFiyat=154000.0m },
            new() { Tip="ITEM", Kod="LL4", Aciklama="4 Axles Low Loader Semi Trailer", Detay="4 Hydraulic Steering Axles (Heavy Duty) BPW or SAF", BirimFiyat=169000.0m },
            new() { Tip="SECTION", Kod="", Aciklama="PRICE LIST WITH TURKISH MADE AXLES", Detay="", BirimFiyat=null },
            new() { Tip="ITEM", Kod="TR2", Aciklama="2 Axles Lowbed Semi Trailer", Detay="1 Fixed - 1 Self Steering Axle TURKISH MADE AXLES", BirimFiyat=46500.0m },
            new() { Tip="ITEM", Kod="TR3", Aciklama="3 Axles Lowbed Semi Trailer", Detay="2 Fixed - 1 Self Steering Axle TURKISH MADE AXLES", BirimFiyat=49200.0m },
            new() { Tip="ITEM", Kod="TR4", Aciklama="4 Axles Lowbed Semi Trailer", Detay="2 Fixed - 2 Self Steering Axle TURKISH MADE AXLES", BirimFiyat=53900.0m },
            new() { Tip="ITEM", Kod="TR5", Aciklama="5 Axles Lowbed Semi Trailer", Detay="3 Fixed - 2 Self Steering Axle TURKISH MADE AXLES", BirimFiyat=59700.0m },
            new() { Tip="ITEM", Kod="TR5", Aciklama="5 Axles Lowbed Semi Trailer", Detay="2 Fixed - 3 Self Steering Axle TURKISH MADE AXLES", BirimFiyat=62000.0m },
            new() { Tip="ITEM", Kod="TR6", Aciklama="6 Axles Lowbed Semi Trailer", Detay="3 Fixed - 3 Self Steering Axle TURKISH MADE AXLES", BirimFiyat=68500.0m },
            new() { Tip="SECTION", Kod="", Aciklama="OPTIONAL FEATURES", Detay="", BirimFiyat=null },
            new() { Tip="ITEM", Kod="A001", Aciklama="Single extendable loading platform", Detay="", BirimFiyat=7200.0m },
            new() { Tip="ITEM", Kod="A002", Aciklama="Double extendable loading platform", Detay="", BirimFiyat=25000.0m },
            new() { Tip="ITEM", Kod="A003", Aciklama="Hydraulic operated heavy duty type single piece loading ramps", Detay="", BirimFiyat=5100.0m },
            new() { Tip="ITEM", Kod="A004", Aciklama="Hydraulic operated heavy duty type double piece loading ramps", Detay="", BirimFiyat=7100.0m },
            new() { Tip="ITEM", Kod="A005", Aciklama="Hydraulic operated light weight type double piece loading ramps", Detay="", BirimFiyat=6350.0m },
            new() { Tip="ITEM", Kod="A006", Aciklama="Hydraulic in and out sliding mechanism for loading ramps", Detay="", BirimFiyat=1650.0m },
            new() { Tip="ITEM", Kod="A007", Aciklama="Detachable ramp system (quick attach and detach in 5 min)", Detay="", BirimFiyat=4650.0m },
            new() { Tip="ITEM", Kod="A008", Aciklama="Aluminium loading ramps with 20 tons capacity per pair", Detay="", BirimFiyat=2000.0m },
            new() { Tip="ITEM", Kod="A009", Aciklama="Aluminium loading ramps with 30 tons capacity per pair", Detay="", BirimFiyat=2500.0m },
            new() { Tip="ITEM", Kod="A010", Aciklama="Hot dipped galvanization for loading ramps", Detay="", BirimFiyat=1150.0m },
            new() { Tip="ITEM", Kod="A011", Aciklama="Short, painted steel head board", Detay="", BirimFiyat=650.0m },
            new() { Tip="ITEM", Kod="A012", Aciklama="Galvanized, short steel head board", Detay="", BirimFiyat=750.0m },
            new() { Tip="ITEM", Kod="A013", Aciklama="Galvanized, long steel head board", Detay="", BirimFiyat=900.0m },
            new() { Tip="ITEM", Kod="A014", Aciklama="Tool box formed steel head board", Detay="", BirimFiyat=1350.0m },
            new() { Tip="ITEM", Kod="A015", Aciklama="Joggle type, aluminium side boards", Detay="", BirimFiyat=500.0m },
            new() { Tip="ITEM", Kod="A016", Aciklama="Fold down type aluminium side boards", Detay="", BirimFiyat=600.0m },
            new() { Tip="ITEM", Kod="A017", Aciklama="Fold down type aluminium side boards with KINNEGRIP pillars", Detay="", BirimFiyat=1300.0m },
            new() { Tip="ITEM", Kod="A018", Aciklama="Joggle type, aluminium close board", Detay="", BirimFiyat=250.0m },
            new() { Tip="ITEM", Kod="A019", Aciklama="Aluminium gooseneck climbing ramps", Detay="", BirimFiyat=1050.0m },
            new() { Tip="ITEM", Kod="A020", Aciklama="Steel gooseneck climbing ramps", Detay="", BirimFiyat=400.0m },
            new() { Tip="ITEM", Kod="A021", Aciklama="Hydraulic liftable gooseneck climbing platform", Detay="", BirimFiyat=6500.0m },
            new() { Tip="ITEM", Kod="A022", Aciklama="1 pair of aluminium bridge with 18 tons capacity L: 1.000 mm", Detay="", BirimFiyat=2100.0m },
            new() { Tip="ITEM", Kod="A023", Aciklama="1 pair of wheel wells with galvanized steel framed wood covers", Detay="", BirimFiyat=3100.0m },
            new() { Tip="ITEM", Kod="A024", Aciklama="Excavator well", Detay="", BirimFiyat=2250.0m },
            new() { Tip="ITEM", Kod="A025", Aciklama="Outrigger woods with galvanized steel frame", Detay="", BirimFiyat=1550.0m },
            new() { Tip="ITEM", Kod="A026", Aciklama="Outrigger woods without galvanized steel frame", Detay="", BirimFiyat=1100.0m },
            new() { Tip="ITEM", Kod="A027", Aciklama="Twist type container lock", Detay="", BirimFiyat=280.0m },
            new() { Tip="ITEM", Kod="A028", Aciklama="Scandinavian type container lock", Detay="", BirimFiyat=280.0m },
            new() { Tip="ITEM", Kod="A029", Aciklama="Marine type container lock", Detay="", BirimFiyat=140.0m },
            new() { Tip="ITEM", Kod="A030", Aciklama="Slots for marine type container lock", Detay="", BirimFiyat=140.0m },
            new() { Tip="ITEM", Kod="A031", Aciklama="Desk for leveling the gooseneck and loading platform (compatible with locks)", Detay="", BirimFiyat=1750.0m },
            new() { Tip="ITEM", Kod="A032", Aciklama="Pillar pockets on the sides of the gooseneck and loading platform", Detay="", BirimFiyat=650.0m },
            new() { Tip="ITEM", Kod="A033", Aciklama="Pillar pocket batches on the loading platform", Detay="", BirimFiyat=750.0m },
            new() { Tip="ITEM", Kod="A034", Aciklama="Hot dipped galvanized pillar set and their holder", Detay="", BirimFiyat=1250.0m },
            new() { Tip="ITEM", Kod="A035", Aciklama="1 pc. black painted, steel tool box located under the loading platform", Detay="", BirimFiyat=350.0m },
            new() { Tip="ITEM", Kod="A036", Aciklama="1pc. stainless steel tool box located under the loading platform", Detay="", BirimFiyat=600.0m },
            new() { Tip="ITEM", Kod="A037", Aciklama="Hot dipped galvanized open storage box located under the loading platform", Detay="", BirimFiyat=600.0m },
            new() { Tip="ITEM", Kod="A038", Aciklama="Hot dipped galvanized full wide open storage box", Detay="", BirimFiyat=1250.0m },
            new() { Tip="ITEM", Kod="A039", Aciklama="1 pc. stainless steel tool box located on the gooseneck", Detay="", BirimFiyat=1200.0m },
            new() { Tip="ITEM", Kod="A040", Aciklama="15 tons capacity, double speed, hydraulic winch with remote control", Detay="", BirimFiyat=5500.0m },
            new() { Tip="ITEM", Kod="A041", Aciklama="13 tons capacity, electric winch with remote control", Detay="", BirimFiyat=2150.0m },
            new() { Tip="ITEM", Kod="A042", Aciklama="10 tons capacity, electric winch with remote control", Detay="", BirimFiyat=1400.0m },
            new() { Tip="ITEM", Kod="A043", Aciklama="8 tons capacity, electric winch with remote control", Detay="", BirimFiyat=1200.0m },
            new() { Tip="ITEM", Kod="A044", Aciklama="1 pc. lift axle", Detay="", BirimFiyat=800.0m },
            new() { Tip="ITEM", Kod="A045", Aciklama="1 pc. spare wheel with its holder", Detay="", BirimFiyat=450.0m },
            new() { Tip="ITEM", Kod="A046", Aciklama="Aluminium rims instead of steel rims ALCOA DURA BRIGHT", Detay="", BirimFiyat=550.0m },
            new() { Tip="ITEM", Kod="A047", Aciklama="Kilometer recorder BPW, SAF or JOST", Detay="", BirimFiyat=300.0m },
            new() { Tip="ITEM", Kod="A048", Aciklama="Tire pressure system only with SAF axles for 2 axles", Detay="", BirimFiyat=2300.0m },
            new() { Tip="ITEM", Kod="A049", Aciklama="Tire pressure system only with SAF axles for 3 axles", Detay="", BirimFiyat=2700.0m },
            new() { Tip="ITEM", Kod="A050", Aciklama="Tire pressure system only with SAF axles for 4 axles", Detay="", BirimFiyat=3100.0m },
            new() { Tip="ITEM", Kod="A051", Aciklama="Tire pressure system only with SAF axles for 5 axles", Detay="", BirimFiyat=3500.0m },
            new() { Tip="ITEM", Kod="A052", Aciklama="Tire pressure system only with SAF axles for 6 axles", Detay="", BirimFiyat=4500.0m },
            new() { Tip="ITEM", Kod="A053", Aciklama="Hydraulic or electro-hydraulic steering system TRIDEC or VSE for 2 axles", Detay="", BirimFiyat=33000.0m },
            new() { Tip="ITEM", Kod="A054", Aciklama="Hydraulic or electro-hydraulic steering system TRIDEC or VSE for 3 axles", Detay="", BirimFiyat=43000.0m },
            new() { Tip="ITEM", Kod="A055", Aciklama="Hydraulic or electro-hydraulic steering system TRIDEC or VSE for 4 axles", Detay="", BirimFiyat=51000.0m },
            new() { Tip="ITEM", Kod="A056", Aciklama="Hydraulic or electro-hydraulic steering system TRIDEC or VSE for 5 axles", Detay="", BirimFiyat=61000.0m },
            new() { Tip="ITEM", Kod="A057", Aciklama="Hydraulic or electro-hydraulic steering system TRIDEC or VSE for 6 axles", Detay="", BirimFiyat=71000.0m },
            new() { Tip="ITEM", Kod="A058", Aciklama="Hydraulic or electro-hydraulic steering system TRIDEC or VSE for 7 axles", Detay="", BirimFiyat=81000.0m },
            new() { Tip="ITEM", Kod="A059", Aciklama="Hydraulic suspension system instead of pneumatic suspension", Detay="", BirimFiyat=5000.0m },
            new() { Tip="ITEM", Kod="A060", Aciklama="4 pcs. extendable overload marker boards", Detay="", BirimFiyat=1050.0m },
            new() { Tip="ITEM", Kod="A061", Aciklama="\"CONVOI EXCEPTIONNEL\" written reflective board", Detay="", BirimFiyat=450.0m },
            new() { Tip="ITEM", Kod="A062", Aciklama="6 pcs. hamburger type stop lamps instead of 4 pcs.", Detay="", BirimFiyat=150.0m },
            new() { Tip="ITEM", Kod="A063", Aciklama="Automatic lubrication system with single pump GROENEVELD", Detay="", BirimFiyat=2800.0m },
            new() { Tip="ITEM", Kod="A064", Aciklama="Automatic lubrication system with double pump GROENEVELD", Detay="", BirimFiyat=3500.0m },
            new() { Tip="ITEM", Kod="A065", Aciklama="Smart Board WABCO", Detay="", BirimFiyat=400.0m },
            new() { Tip="ITEM", Kod="A066", Aciklama="Full body metallization with 85% zinc, 15% aluminium (15 years anti-rust warranty)", Detay="", BirimFiyat=3000.0m },
            new() { Tip="ITEM", Kod="A067", Aciklama="Partial metallization with 85% zinc, 15% aluminium (15 years anti-rust warranty)", Detay="", BirimFiyat=1000.0m },
            new() { Tip="ITEM", Kod="A068", Aciklama="Hydraulic support legs under the loading platform tail", Detay="", BirimFiyat=2250.0m },
            new() { Tip="ITEM", Kod="A069", Aciklama="Hydraulic gooseneck", Detay="", BirimFiyat=8900.0m },
        };

        /// <summary>Dil koduna gore (TR/EN) liste dondurur. Diger diller icin TR fallback.</summary>
        public static List<OmRow> ForDil(string? dil)
        {
            return string.Equals(dil, "EN", System.StringComparison.OrdinalIgnoreCase) ? EN : TR;
        }
    }
}
